### ISSUE TITLE
Crash on nil pointer dereference while reading from RemoteDB

### ISSUE THREAD

**Issue by jkrcma** [EvanPurkhiser/prolink-go#7]
I have a track bought from Google Play: _Stonebank - By Your Side (feat. Emel)_ which crashes the app everytime it is played. Found out that it is the `Label` field which causes the exception, however there are no visible metadata under this field inside the ID3. As a workaround I hardcoded empty string instead of the actual data and it worked.

Panic log (don't mind that `/root`, it's inside a LXD container ;)):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x68515b]

goroutine 54 [running]:
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink.(*RemoteDB).queryTrackMetadata(0xc4200da280, 0xc420039cfc, 0xc4202120f8, 0xc420210318, 0x12ad3a7a884ba801)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/remotedb.go:295 +0x3cb
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink.(*RemoteDB).executeQuery(0xc4200da280, 0xc420039cfc, 0x0, 0x0, 0x0)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/remotedb.go:233 +0xf5
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink.(*RemoteDB).GetTrack(0xc4200da280, 0xc420039cfc, 0xe, 0xc42021c0f0, 0x6d4e00)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/remotedb.go:216 +0xaa
go.evanpurkhiser.com/prolink-overlay/server.(*StatusMapper).trackMetadata(0xc42022c4b0, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/server/json.go:130 +0x50
go.evanpurkhiser.com/prolink-overlay/server.(*StatusMapper).trackStatus(0xc42022c4b0, 0x757611, 0xb, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/server/json.go:146 +0x149
go.evanpurkhiser.com/prolink-overlay/server.(*StatusMapper).(go.evanpurkhiser.com/prolink-overlay/server.trackStatus)-fm(0x757611, 0xb, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/server/json.go:103 +0x48
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus.(*Handler).reportPlayer(0xc420210360, 0xc420234504)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus/handler.go:152 +0x15a
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus.(*Handler).trackMayBeFirst(0xc420210360, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus/handler.go:256 +0x120
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus.(*Handler).playStateChange(0xc420210360, 0xc42025c1e0, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus/handler.go:274 +0x387
go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus.(*Handler).OnStatusUpdate(0xc420210360, 0xc42001e330)
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/trackstatus/handler.go:330 +0x48c
created by go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink.(*CDJStatusMonitor).activate.func1
        /root/go/src/go.evanpurkhiser.com/prolink-overlay/vendor/go.evanpurkhiser.com/prolink/status.go:233 +0x107
```

Thank you for your amazing work btw!

**Comment by EvanPurkhiser** [comment]
Super late on the response to these PRs, but - You don't happen to still have this track and would be able to email this to me would you?

Also I'm interested in what you're doing with a LXD container :) A workaround to running on the same host as rekordbox perphase?

**Comment by jkrcma** [comment]
Haha I see :D I can send it to you, hopefully the ID3 remained unchanged since then.

I was running it in LXD container (on my NAS) because it was FAR easier to build the project in real Linux environment rather than in Windows Subsystem for Linux, and it handles the "same IP issue" as well

**Comment by EvanPurkhiser** [comment]
Thanks! I'll have a go at testing soon :) You don't happen to have any idea what version you built do you? Unfortunately I only recently even had the program report it's version.

**Comment by jkrcma** [comment]
I do not however my container remembers :) `cc41bf0`

**Comment by EvanPurkhiser** [comment]
I can't seem to reproduce this. Going to close for now. The new [`prolink-server`](https://github.com/EvanPurkhiser/prolink-tools/tree/serve) has sentry setup in it, so I should be able to get better insight into errors in the future.
